CREATE TABLE IF NOT EXISTS atlas_driver_offer_bpp.merchant_push_notification
(
    merchant_id character(36) NOT NULL,
    push_notification_key character varying(255) not null,
    language character varying(255) not null,
    udf1 character varying(255),
    notification_sub_type character varying(255) not null,
    icon character varying(255),
    title text not null,
    body text not null
);

INSERT INTO atlas_driver_offer_bpp.merchant_push_notification (merchant_id, push_notification_key, language, udf1, notification_sub_type, icon, title, body) VALUES
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'ENGLISH', 'PAYMENT_FAILED_AUTOPAY', 'Z9', 'LOW_ACCOUNT_BALANCE', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_save_more', 'Low Account Balance', 'Your Bank Account balance is low.<br>Add <b> \\u20B9 {#dueAmount#} </b> to enjoy uninterrupted rides.'),
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'ENGLISH', 'PAYMENT_FAILED_MANUAL', 'Z9', 'PAYMENT_FAILED_LOW_ACCOUNT_BALANCE', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_save_more', 'Payment Failed', '<b>Low Account Balance.</b><br>Please add  <b> \\u20B9 {#dueAmount#} </b> in your bank account and retry payment.'),
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'ENGLISH', 'PLAN_SWITCH', null, 'SWITCH_PLAN', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_save_more', 'Save more with\n DAILY UNLIMITED', 'You have completed {#numberOfRides#} rides today. Save up to {#saveUpto#} by switching to the DAILY UNLIMITED plan'),
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'ENGLISH', 'PAYMENT_PENDING', 'AUTOPAY', 'PAYMENT_PENDING_AUTOPAY_SET', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_pending', 'Payment Pending', 'To continue taking rides on Namma Yatri, clear your payment dues'),
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'ENGLISH', 'PAYMENT_PENDING', 'MANUAL', 'PAYMENT_PENDING_AUTOPAY_NOT_SET', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_pending', 'Payment Pending', 'To continue taking rides on Namma Yatri, clear your payment dues'),
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'ENGLISH', 'PAYMENT_FAILED_AUTOPAY', null, 'AUTOPAY_PAYMENT_FAILED', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_autopay_payment_failed', 'Autopay Payment Failed', 'Clear your Manual dues for hassle-free rides!'),
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'ENGLISH', 'PAYMENT_FAILED_MANUAL', null, 'MANUAL_PAYMENT_FAILED', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_failed', 'Payment Failed', 'Clear your Manual dues for hassle-free rides.'),
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'KANNADA', 'PAYMENT_FAILED_AUTOPAY', 'Z9', 'LOW_ACCOUNT_BALANCE', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_save_more', 'ಕಡಿಮೆ ಖಾತೆ ಬ್ಯಾಲೆನ್ಸ್', 'ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಯ ಬ್ಯಾಲೆನ್ಸ್ ಕಡಿಮೆಯಾಗಿದೆ.<br> <b> \\u20B9 {#dueAmount#} </b> ಅಡೆತಡೆಯಿಲ್ಲದ ಸವಾರಿಗಳನ್ನು ಆನಂದಿಸಲು.'),
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'KANNADA', 'PAYMENT_FAILED_MANUAL', 'Z9', 'PAYMENT_FAILED_LOW_ACCOUNT_BALANCE', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_save_more', 'ಪಾವತಿ ವಿಫಲವಾಗಿದೆ', '<b>ಕಡಿಮೆ ಖಾತೆ ಬಾಕಿ.</b><br>ದಯವಿಟ್ಟು <b> \\u20B9 {#dueAmount#} </b> ಅನ್ನು ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಯಲ್ಲಿ ಸೇರಿಸಿ ಮತ್ತು ಪಾವತಿಯನ್ನು ಮರುಪ್ರಯತ್ನಿಸಿ.'),
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'KANNADA', 'PLAN_SWITCH', null, 'SWITCH_PLAN', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_save_more', 'ಪ್ರತಿದಿನ ಅನ್ಲಿಮಿಟೆಡ್\n ಜೊತೆಗೆ ಇನ್ನಷ್ಟು ಉಳಿಸಿ', 'ನೀವು ಇಂದು {#numberOfRides#} ರೈಡ್‌ಗಳನ್ನು ಪೂರ್ಣಗೊಳಿಸಿದ್ದೀರಿ. ಡೆಯ್ಲಿ ಆನ್ಲಿಮಿಟೆಡ್ ಜೊತೆಗೆ ಪ್ಲಾನ್ ಗೆ ಬದಲಾಯಿಸುವ ಮೂಲಕ {#saveUpto#} ವರೆಗೆ ಉಳಿಸಿ'),
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'KANNADA', 'PAYMENT_PENDING', 'AUTOPAY', 'PAYMENT_PENDING_AUTOPAY_SET', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_pending', 'ಪಾವತಿ ಬಾಕಿ ಇದೆ', 'ನಮ್ಮ ಯಾತ್ರಿಯಲ್ಲಿ ಸವಾರಿ ಮಾಡುವುದನ್ನು ಮುಂದುವರಿಸಲು, ನಿಮ್ಮ ಪಾವತಿ ಬಾಕಿಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ'),
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'KANNADA', 'PAYMENT_PENDING', 'MANUAL', 'PAYMENT_PENDING_AUTOPAY_NOT_SET', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_pending', 'ಪಾವತಿ ಬಾಕಿ ಇದೆ', 'ನಮ್ಮ ಯಾತ್ರಿಯಲ್ಲಿ ಸವಾರಿ ಮಾಡುವುದನ್ನು ಮುಂದುವರಿಸಲು, ನಿಮ್ಮ ಪಾವತಿ ಬಾಕಿಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ'),
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'KANNADA', 'PAYMENT_FAILED_AUTOPAY', null, 'AUTOPAY_PAYMENT_FAILED', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_autopay_payment_failed', 'ಆಟೋಪೆ ಪಾವತಿ ವಿಫಲ', 'ಜಗಳ ಮುಕ್ತ ಸವಾರಿಗಳಿಗಾಗಿ ನಿಮ್ಮ ಮನುಲ ದುಸ್ ಅನ್ನು ತೆರವುಗೊಳಿಸಿ!'),
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'KANNADA', 'PAYMENT_FAILED_MANUAL', null, 'MANUAL_PAYMENT_FAILED', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_failed', 'ಪಾವತಿ ವಿಫಲವಾಗಿದೆ', 'ಜಗಳ ಮುಕ್ತ ಸವಾರಿಗಳಿಗಾಗಿ ನಿಮ್ಮ ಮನುಲ ದುಸ್ ಅನ್ನು ತೆರವುಗೊಳಿಸಿ!'),
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'HINDI', 'PAYMENT_FAILED_AUTOPAY', 'Z9', 'LOW_ACCOUNT_BALANCE', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_save_more', 'कम खाता शेष', 'आपके बैंक खाते का बैलेंस कम है। निर्बाध सवारी का आनंद लेने के लिए<br> <b> \\u20B9 {#dueAmount#} </b> जोड़ें।'),
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'HINDI', 'PAYMENT_FAILED_MANUAL', 'Z9', 'PAYMENT_FAILED_LOW_ACCOUNT_BALANCE', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_save_more', 'भुगतान विफल', '<b>कम खाता शेष।</b><br>कृपया अपने बैंक खाते में <b> \\u20B9 {#dueAmount#} </b> जोड़ें और भुगतान का पुनः प्रयास करें।'),
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'HINDI', 'PLAN_SWITCH', null, 'SWITCH_PLAN', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_save_more', 'डेली अनलिमिटेड\n के साथ अधिक बचत करें', 'आपने आज {#numberOfRides#} सवारी पूरी कर ली है। डेली अनलिमिटेड प्लान पर स्विच करके {#saveUpto#} तक की बचत करें')
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'HINDI', 'PAYMENT_PENDING', 'AUTOPAY', 'PAYMENT_PENDING_AUTOPAY_SET', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_pending', 'भुगतान लंबित', 'नम्मा यात्री पर यात्रा जारी रखने के लिए, अपना बकाया भुगतान चुकाएं')
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'HINDI', 'PAYMENT_PENDING', 'MANUAL', 'PAYMENT_PENDING_AUTOPAY_NOT_SET', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_pending', 'भुगतान लंबित', 'नम्मा यात्री पर यात्रा जारी रखने के लिए, अपना बकाया भुगतान चुकाएं')
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'HINDI', 'PAYMENT_FAILED_AUTOPAY', null, 'AUTOPAY_PAYMENT_FAILED', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_autopay_payment_failed', 'ऑटोपे भुगतान विफल', 'परेशानी मुक्त सवारी के लिए अपना मैन्युअल बकाया चुकाएं!')
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'HINDI', 'PAYMENT_FAILED_MANUAL', null, 'MANUAL_PAYMENT_FAILED', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_failed', 'भुगतान विफल', 'परेशानी मुक्त सवारी के लिए अपना मैन्युअल बकाया चुकाएं!')
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'TAMIL', 'PAYMENT_FAILED_AUTOPAY', 'Z9', 'LOW_ACCOUNT_BALANCE', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_save_more', 'குறைந்த கணக்கு இருப்பு', 'உங்கள் பேங்க் அக்கவுண்ட் பேலன்ஸ் குறைவாக உள்ளது.<br>தடையின்றி சவாரி செய்ய <b> \\u20B9 {#dueAmount#} </b> ஐ சேர்க்கவும்.')
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'TAMIL', 'PAYMENT_FAILED_MANUAL', 'Z9', 'PAYMENT_FAILED_LOW_ACCOUNT_BALANCE', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_save_more', 'கொடுப்பன தோல்வி', '<b>குறைந்த கணக்கு இருப்பு.</b><br>உங்கள் பேங்க் அக்கவுண்ட் பேலன்ஸ் குறைவாக உள்ளது. <b> \\u20B9 {#dueAmount#} </b> ஐ உங்கள் பேங்க் அக்கவுண்ட் இலக்கில் சேர்க்கவும், மீண்டும் கொடுப்பனை முயற்சிக்க.')
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'TAMIL', 'PLAN_SWITCH', null, 'SWITCH_PLAN', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_save_more', 'டெய்லி அன்லிமிடெட்\n உட்கொண்டு மேல்படி சேமிக்க', 'நீங்கள் இன்று {#numberOfRides#} சவாரி முடித்துவிட்டீர்கள். டெய்லி அன்லிமிடெட் திட்டத்தில் மாற்றியிருந்தால், மீர்பட <b> \\u20B9 {#saveUpto#} </b> குறைவாக்கவும்')
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'TAMIL', 'PAYMENT_PENDING', 'AUTOPAY', 'PAYMENT_PENDING_AUTOPAY_SET', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_pending', 'கொடுப்பன் முடிக்கவில்லை', 'சவாரி செய்ய தொடர உங்கள் கொடுப்பன் பேன்ஸ் கொடுக்க')
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'TAMIL', 'PAYMENT_PENDING', 'MANUAL', 'PAYMENT_PENDING_AUTOPAY_NOT_SET', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_payment_pending', 'கொடுப்பன் முடிக்கவில்லை', 'சவாரி செய்ய தொடர உங்கள் கொடுப்பன் பேன்ஸ் கொடுக்க')
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'TAMIL', 'PAYMENT_FAILED_AUTOPAY', null, 'AUTOPAY_PAYMENT_FAILED', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_ic_autopay_payment_failed', 'ஆட்டோபே கொடுப்பன் தோல்வி', 'விலக்குவத்தின் திவள் சவாரிகளுக்காக, உங்கள் மைனியூல் கொடுப்பன்ஸ் வெற்றிகரமாக தொடர்வை தெரிவிக்கவும்!')
    ('7f7896dd-787e-4a0b-8675-e9e6fe93bb8f', 'TAMIL', 'PAYMENT_FAILED_MANUAL', null, 'MANUAL_PAYMENT_FAILED', 'https://assets.juspay.in/beckn/nammayatri/driver/images/ny_failed', 'கொடுப்பன் தோல்வி', 'விலக்குவத்தின் திவள் சவாரிகளுக்காக, உங்கள் மைனியூல் கொடுப்பன்ஸ் வெற்றிகரமாக தொடர்வை தெரிவிக்கவும்!');


ALTER TABLE atlas_driver_offer_bpp.payment_order ALTER COLUMN amount type numeric(30,2);